-- AI Tables for caching insights, forecasts and budget suggestions
-- Run this SQL in your Supabase SQL Editor

-- 1. Insights cache: generated by Groq LLM based on monthly transaction data
CREATE TABLE IF NOT EXISTS ai_insights (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  month text NOT NULL,
  type text NOT NULL CHECK (type IN ('anomalies', 'trends', 'budget', 'savings')),
  content jsonb NOT NULL,
  generated_at timestamptz DEFAULT now(),
  model text DEFAULT 'groq-llama-3.1-8b-instant',
  UNIQUE(user_id, month, type)
);

-- 2. Expense predictions: LLM-generated forecasts per category per month
CREATE TABLE IF NOT EXISTS expense_predictions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  target_month text NOT NULL,
  category text NOT NULL,
  predicted_amount numeric NOT NULL,
  confidence_low numeric,
  confidence_high numeric,
  reasoning text,
  trend text CHECK (trend IN ('up', 'down', 'stable')),
  change_percent numeric,
  generated_at timestamptz DEFAULT now(),
  model text DEFAULT 'groq-llama-3.1-8b-instant',
  UNIQUE(user_id, target_month, category)
);

-- 3. Budget suggestions: LLM-generated optimization recommendations
CREATE TABLE IF NOT EXISTS budget_suggestions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  suggested_at timestamptz DEFAULT now(),
  suggestions jsonb NOT NULL,
  summary text,
  model text DEFAULT 'groq-llama-3.1-8b-instant'
);

-- 4. Indexes for fast cache lookups
CREATE INDEX IF NOT EXISTS idx_ai_insights_user_month ON ai_insights(user_id, month);
CREATE INDEX IF NOT EXISTS idx_expense_predictions_user_month ON expense_predictions(user_id, target_month);
CREATE INDEX IF NOT EXISTS idx_budget_suggestions_user_date ON budget_suggestions(user_id, suggested_at DESC);

-- 5. Enable Row Level Security on all tables
ALTER TABLE ai_insights ENABLE ROW LEVEL SECURITY;
ALTER TABLE expense_predictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE budget_suggestions ENABLE ROW LEVEL SECURITY;

-- 6. RLS Policies: users can only access their own data
CREATE POLICY "Users can view their own insights"
  ON ai_insights FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own insights"
  ON ai_insights FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own insights"
  ON ai_insights FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own insights"
  ON ai_insights FOR DELETE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can view their own predictions"
  ON expense_predictions FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own predictions"
  ON expense_predictions FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own predictions"
  ON expense_predictions FOR DELETE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can view their own suggestions"
  ON budget_suggestions FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own suggestions"
  ON budget_suggestions FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own suggestions"
  ON budget_suggestions FOR DELETE
  USING (auth.uid() = user_id);