name: Backup to GitLab

on:
  push:
    branches:
      - main
      - develop
      - test
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git remote add gitlab https://gitlab.com/bernardo.ferreira2-group/family-finance-new.git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git push --all gitlab --force
          git push --tags gitlab --force
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_PASSWORD }}
